services:
  postgres:
    image: postgres:17
    container_name: raspi5-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: raspi
      POSTGRES_PASSWORD: raspi_password
      POSTGRES_DB: control_center

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
